spring:
  datasource:
    url: jdbc:postgresql://postgres-service:5432/bid
    username: Amir
    password: Amir
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: BidWinner:com.ms.ecommerce.kafka.BidWinner
server:
  port: 8070
application:
  config:
    client-url: http://client-service:8090/api/v1/client
    product-url: http://product-service:8050/api/v1/product
    payment-url: http://payment-service:8060/api/v1/payment
