spring:
  data:
    mongodb:
      username: amir
      password: amir
      host: mongo-service
      port: 27017
      database: client-service
      authentication-database: admin
server:
  port: 8090