spring:
  datasource:
    url: jdbc:postgresql://postgres-service:5432/payment
    username: Amir
    password: Amir
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: PaymentNotification:com.ms.ecommerce.notification.PaymentNotification
server:
  port: 8060