apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  labels:
    app: notification-deployment
spec:
  replicas: 1          # Number of pod replicas
  selector:
    matchLabels:
      app: notification-deployment
  template:
    metadata:
      labels:
        app: notification-deployment
    spec:
      containers:
        - name: notification-deployment
          image: abdellaouiamir/notification:1.0.0    # Replace with your Docker image name
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.2"
            limits:
              memory: "512Mi"
              cpu: "0.5"