apiVersion: v1
kind: Service
metadata:
  name: bid-service
  labels:
    app: bid-deployment
spec:
  selector:
    app: bid-deployment
  ports:
    - port: 8070  # Container port
      protocol: TCP
  type: ClusterIP    # Use NodePort or ClusterIP if you don't need external access
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid-deployment
  labels:
    app: bid-deployment
spec:
  replicas: 1          # Number of pod replicas
  selector:
    matchLabels:
      app: bid-deployment
  template:
    metadata:
      labels:
        app: bid-deployment
    spec:
      containers:
        - name: bid-deployment
          image: abdellaouiamir/bid:1.0.1    # Replace with your Docker image name
          imagePullPolicy: IfNotPresent  # Use Always if pulling from remote registry
          ports:
            - containerPort: 8070
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.2"
            limits:
              memory: "512Mi"
              cpu: "0.5"