apiVersion: v1
kind: Service
metadata:
  name: config-server-service
  labels:
    app: config-server-deployment
spec:
  selector:
    app: config-server-deployment
  ports:
    - port: 8888          # External port
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
  labels:
    app: config-server-deployment
spec:
  replicas: 1          # Number of pod replicas
  selector:
    matchLabels:
      app: config-server-deployment
  template:
    metadata:
      labels:
        app: config-server-deployment
    spec:
      containers:
        - name: config-server-deployment
          image: abdellaouiamir/config_server:latest
          ports:
            - containerPort: 8888
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.2"
            limits:
              memory: "512Mi"
              cpu: "0.5"