apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;

        location /api/v1/bid/ {
          proxy_pass http://bid-service:8070/;
        }

        location /api/v1/client/ {
          proxy_pass http://client-service:8090/;
        }

        location /api/v1/product/ {
          proxy_pass http://product-service:8050/;
        }
    
        location /api/v1/category/ {
          proxy_pass http://product-service:8050/;
        }

        location /api/v1/payment/ {
          proxy_pass http://payment-service:8060/;
        }

        location /api/v1/notification/ {
          proxy_pass http://notification-service:8040/;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-gateway
  template:
    metadata:
      labels:
        app: nginx-gateway
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway-service
spec:
  selector:
    app: nginx-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Use NodePort or ClusterIP based on your needs