apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-deployment
spec:
  selector:
    app: payment-deployment
  ports:
    - port: 8060          # External port
      protocol: TCP
  type: ClusterIP    # Use NodePort or ClusterIP if you don't need external access
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: payment-deployment
spec:
  replicas: 1          # Number of pod replicas
  selector:
    matchLabels:
      app: payment-deployment
  template:
    metadata:
      labels:
        app: payment-deployment
    spec:
      containers:
        - name: payment-deployment
          image: abdellaouiamir/payment:latest    # Replace with your Docker image name
          ports:
            - containerPort: 8060
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.2"
            limits:
              memory: "512Mi"
              cpu: "0.5"