apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: client-deployment
spec:
  selector:
    app: client-deployment
  ports:
    - port: 8090  # Container port
      protocol: TCP
  type: ClusterIP    # Use NodePort or ClusterIP if you don't need external access
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client-deployment
spec:
  replicas: 1          # Number of pod replicas
  selector:
    matchLabels:
      app: client-deployment
  template:
    metadata:
      labels:
        app: client-deployment
    spec:
      containers:
        - name: client-deployment
          image: abdellaouiamir/client:latest
          ports:
            - containerPort: 8090
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.2"
            limits:
              memory: "512Mi"
              cpu: "0.5"