# mongodb.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "amir"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "amir"
          volumeMounts:
            - name: mongo-storage
              mountPath: "/data/db"
          ports:
            - containerPort: 27017
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: microservices
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb